spring:
  config:
    import: optional:configserver:http://localhost:8888  # Import from Config Server (optional)
  cloud:
    config:
      uri: http://localhost:8888   # URL of your Config Server
      fail-fast: false             # Don't fail if Config Server is not available initially
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: auth
              uri: http://localhost:8001
              predicates:
                - Path=/api/v1/auth/**
            - id: user
              uri: http://localhost:8002
              predicates:
                - Path=/api/v1/user/**

  application:
    name: api-gateway

server:
  port: 8764

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    initial-instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 30
